### ISSUE TITLE
Threads

### ISSUE THREAD

**Issue by mazulo** [mazulo/pynews_cli#2]
The script should use thread if the user want it: something like `--threads 4`

**Comment by drgarcia1986** [comment]
:hand:  I can help!

**Comment by mazulo** [comment]
I noted that I made PyNews only works with Python 3 (because if you run it with Python 2 will raise an `ImportError: No module named concurrent.futures` exception). So we could think in a way to do that

**Comment by drgarcia1986** [comment]
No problem https://pypi.python.org/pypi/futures :smile: 
(we have to be careful with `print()` function too)
