### ISSUE TITLE
Informação do ambiente de teste em prod

### ISSUE THREAD

**Issue by gigante** [mazulo/pynews_cli#3]
## Comando executado

$ pip install pynews
$ pynews -t 10
## O que apareceu:

`/home/mazulo/.virtualenvs/test_pynews/bin/python: interpretador inválido: Arquivo ou diretório não encontrado`
## O que estou usando:

Python 3.5.1
[Pyenv](https://github.com/yyuu/pyenv)

**Comment by mazulo** [comment]
Um amigo relatou esse mesmo erro há poucos minutos antes. Tô tentando descobrir o motivo disso (já que vc pode ver que nos arquivos não há essa informação da minha env para ser enviada).

**Comment by mazulo** [comment]
@gigante você pode fazer um `pip install -U pynews`? Encontrei aqui e testei no PC de um amigo aqui do lado que estava com o mesmo problema e resolveu

**Comment by gigante** [comment]
Good Work!! Tá lindo agora :)

**Comment by gigante** [comment]
Eu sei que poderia ser outra issue... hehehe

Era interessante ter uma quantidade default de notícias a serem carregadas! com o comando `pynews`
