### ISSUE TITLE
Quantidade default de notícias a serem carregadas

### ISSUE THREAD

**Issue by gigante** [mazulo/pynews_cli#5]
Era interessante ter uma quantidade default de notícias a serem carregadas! 
Apenas com o comando `pynews`

**Comment by mazulo** [comment]
E havia, só que eu tive que [retirar](https://github.com/mazulo/pynews_cli/commit/fc43d9a12e7dd31f19000defaf099dc278b6b30c#diff-c07acb74a3181374bfe23986c9d171e1L44) até eu refazer um flow. Com a quantidade sendo default acabei me deparando com uma situação inesperada hahaha daí que daqui pro final de semana consigo reorganizar para voltar novamente :smile:

**Comment by gigante** [comment]
Tranquilidade... ainda nem olhei o codigo... hehehe
Vou dar uma olhada atenta pra ver se ajudo em alguma coisa :)

**Comment by mazulo** [comment]
Se vc puder, tem 2 tretas pra resolver: uma da issue #6 que acabei de criar, e outra relacionada com um erro `ImportError: No module named 'pynews'` quando eu edito o shebang do `bin/pynews` de `#!/usr/bin/python` para `#!/usr/bin/python3` (uma tentativa de resolver o problema de compatibilidade).

**Comment by drgarcia1986** [comment]
Sobre a quantidade default já tem (só ta bem alta).
A issue #6 já está resolvida :smile: 
Sobre o shebang, talvez não seja mais necessário graças ao uso do entrypoint ( #8 )
